name: delete-testing-packages

on:
  workflow_dispatch:

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.8.1
        with:
          token: ${{ secrets.GH_PACKAGES_TOKEN }}
          user: engels74
          type: container
          version-pattern: "^testing.*$"  # Matches 'testing' followed by anything
          keep: 0
          dry-run: false
          names: |
            tgraph-bot
