name: update-upstream-packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Login to ghcr.io
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Do Work
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          PERSONAL_TOKEN:   ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK:  ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          while IFS= read -r REPOSITORY; do
            while IFS= read -r BRANCH; do
              git clone -b "${BRANCH}" "https://${PERSONAL_TOKEN}@github.com/${REPOSITORY_OWNER}/${REPOSITORY}.git"
              cd "${REPOSITORY}" || exit 1
              ###########################################
              if [[ "${BRANCH}" != *pr ]]; then
                docker run --rm --entrypoint="" -v ./:/repo -e PACKAGES_HASH="/repo/packages-hash.log" "ghcr.io/${REPOSITORY_OWNER}/${REPOSITORY}:${BRANCH}" sh -c 'if grep -q alpine < /etc/os-release; then apk upgrade --no-cache --available && apk -vv info | sort | sha1sum | cut -f 1 -d " " > ${PACKAGES_HASH}; else export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get upgrade -y && apt list --installed | sha1sum | cut -f 1 -d " " > ${PACKAGES_HASH}; fi'
                hash_old=$(jq -r '.packages_hash' < meta.json)
                hash_new=$(cat packages-hash.log)
                json=$(cat meta.json)
                jq --sort-keys \
                    --arg packages_hash "${hash_new}" \
                    '.packages_hash = $packages_hash' <<< "${json}" | tee meta.json
                if [[ "${hash_old}" != "${hash_new}" ]]; then
                  packages_commit_message="Packages hash change: ${hash_old} => ${hash_new}"
                  packages_discord_message="Packages hash change detected: \`${hash_old}\` => \`${has_new}\`"
                fi
              fi
              upstream_tag_sha_old=$(jq -r '.upstream_tag_sha' < meta.json)
              if [[ -f update-upstream.sh ]]; then
                bash update-upstream.sh || true
              else
                continue
              fi
              upstream_tag_sha_new="$(jq -re '.upstream_tag_sha' < meta.json)"
              if [[ "${upstream_tag_sha_old}" != "${upstream_tag_sha_new}" ]]; then
                upstream_commit_message="Upstream update: ${upstream_tag_sha_old} => ${upstream_tag_sha_new}"
                upstream_discord_message="Upstream changes detected: \`${upstream_tag_sha_old}\` => \`${upstream_tag_sha_new}\`"
              fi
              [[ -n "${packages_commit_message}" ]] && commit_message=" / ${packages_commit_message}"
              [[ -n "${upstream_commit_message}" ]] && commit_message="${upstream_commit_message}${commit_message}" || commit_message="${packages_commit_message}"
              [[ -n "${packages_discord_message}" ]] && discord_message=" / ${packages_discord_message}"
              [[ -n "${upstream_discord_message}" ]] && discord_message="${upstream_discord_message}${discord_message}" || discord_message="${packages_discord_message}"
              [[ "${BRANCH}" == *pr ]] && commit_message="${commit_message} [skip ci]"
              git add meta.json
              if git commit -m "${commit_message}"; then
                git push
                GIT_SHA=$(git log -n 1 --pretty=format:"%H")
                json=$(jq -nc --arg     title       "${REPOSITORY_OWNER}/${REPOSITORY}:${BRANCH}" \
                              --arg     url         "https://github.com/${REPOSITORY_OWNER}/${REPOSITORY}/commit/${GIT_SHA}" \
                              --arg     description "${discord_message}" \
                              --argjson color       "4886754" \
                              --arg     timestamp   "$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")" \
                              '{"embeds": [
                                {
                                  "title": $title,
                                  "url": $url,
                                  "description": $description,
                                  "color": $color,
                                  "footer": {"text": "Powered by GitHub Actions"},
                                  "timestamp": $timestamp
                                }
                              ]}')
                jq <<< "${json}"
                curl -fsSL -X POST -H "Content-Type: application/json" -d "${json}" "${DISCORD_WEBHOOK}"
              fi
              ###########################################
              cd .. || exit 1
              rm -rf "${REPOSITORY}"
            done < <(curl -fsSL --header "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/repos/${REPOSITORY_OWNER}/${REPOSITORY}/branches" | jq -re '.[] | select(.name!="master") | .name')
          done < <(curl -fsSL --header "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/users/${REPOSITORY_OWNER}/repos?per_page=1000" | jq -re '.[] | select(.topics[]=="docker-image") | .name')
