name: update-packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1-23/2 * * *'

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - name: Git Config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Do Work
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          PERSONAL_TOKEN:   ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
          DISCORD_WEBHOOK:  ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          while IFS= read -r REPOSITORY; do
            while IFS= read -r BRANCH; do
              git clone -b "${BRANCH}" "https://${PERSONAL_TOKEN}@github.com/${REPOSITORY_OWNER}/${REPOSITORY}.git"
              cd "${REPOSITORY}" || exit 1
              ###########################################
              docker run --rm --entrypoint="" -v ${REPOSITORY}:/repo -e PACKAGES_HASH="/repo/packages-hash.log" "${REPOSITORY_OWNER}/${REPOSITORY}:${BRANCH}" sh -c 'if grep -q alpine < /etc/os-release; then apk update --no-cache && apk upgrade --no-cache --available && apk -vv info | sort | sha1sum | awk '{print $1}' > ${PACKAGES_HASH}; else export DEBIAN_FRONTEND="noninteractive" && apt-get update && apt-get upgrade -y && apt list --installed | sha1sum | awk '{print $1}' > ${PACKAGES_HASH}; fi'
              old_hash="$(jq -r '.packages_hash' < meta.json)"
              json=$(cat meta.json)
              jq --sort-keys \
                  --arg packages_hash "$(cat packages-hash.log)" \
                  '.packages_hash = $packages_hash' <<< "${json}" | tee meta.json
              if new_hash="$(jq -re '.packages_hash' < meta.json)"; then
                commit_message="Packages update: ${old_hash} => ${new_hash}"
                discord_message="Packages changes detected: \`${old_hash}\` => \`${new_hash}\`"
              else
                commit_message="Packages update"
                discord_message="Packages changes detected."
              fi
              [[ "${BRANCH}" == *pr ]] && commit_message="${commit_message} [skip ci]"
              git add meta.json
              if git commit -m "${commit_message}"; then
                git push
                GIT_SHA=$(git log -n 1 --pretty=format:"%H")
                json=$(jq -nc --arg     title       "${REPOSITORY_OWNER}/${REPOSITORY}:${BRANCH}" \
                              --arg     url         "https://github.com/${REPOSITORY_OWNER}/${REPOSITORY}/commit/${GIT_SHA}" \
                              --arg     description "${discord_message}" \
                              --argjson color       "4886754" \
                              --arg     timestamp   "$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")" \
                              '{"embeds": [
                                {
                                  "title": $title,
                                  "url": $url,
                                  "description": $description,
                                  "color": $color,
                                  "footer": {"text": "Powered by GitHub Actions"},
                                  "timestamp": $timestamp
                                }
                              ]}')
                jq <<< "${json}"
                curl -fsSL -X POST -H "Content-Type: application/json" -d "${json}" "${DISCORD_WEBHOOK}"
              fi
              ###########################################
              cd .. || exit 1
              rm -rf "${REPOSITORY}"
            done < <(curl -fsSL --header "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/repos/${REPOSITORY_OWNER}/${REPOSITORY}/branches" | jq -re '.[] | select(.name!="master") | .name')
          done < <(curl -fsSL --header "Authorization: Bearer ${GITHUB_TOKEN}" "https://api.github.com/users/${REPOSITORY_OWNER}/repos?per_page=1000" | jq -re '.[] | select(.topics[]=="docker-image") | .name')
